name: Pipeline Node App

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    name: 1. Validar Calidad del Código
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Pruebas y Linter
        run: |
          npm run lint || echo "Sin linter definido"
          npm run test
